// apps/react/src/App.tsx
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import ArticlePage from './pages/ArticlePage'
import EditorPage from './pages/EditorPage'
import HomePage from './pages/HomePage'
import LoginPage from './pages/LoginPage'
import ProfilePage from './pages/ProfilePage'
import RegisterPage from './pages/RegisterPage'
import SettingsPage from './pages/SettingsPage'
import { useEffect } from 'react'
import { useAuthStore } from './stores/authStore'

const RequireAuth = () => {
  const { isAuthenticated, loading, bootstrapped } = useAuthStore()
  const location = useLocation()

  if (!bootstrapped || loading)
    return <p className="helper-text" style={{ padding: '1rem' }}>Loading...</p>
  if (!isAuthenticated) return <Navigate to={`/login?redirect=${encodeURIComponent(location.pathname + location.search)}`} />
  return <Outlet />
}

const NavBar = () => {
  const { isAuthenticated, user, logout } = useAuthStore()
  const navigate = useNavigate()
  const location = useLocation()

  const isActive = (path: string) => location.pathname === path
  const isEditorActive = location.pathname.startsWith('/editor')
  const isProfileActive = user && location.pathname.startsWith(`/profile/${user.username}`)

  return (
    <header className="navbar">
      <div className="container navbar-content">
        <Link to="/" className="navbar-logo">
          conduit
        </Link>
        <nav className="navbar-links">
          <Link className={`navbar-link ${isActive('/') ? 'active' : ''}`} to="/">
            Home
          </Link>
          {isAuthenticated ? (
            <>
              <Link className={`navbar-link ${isEditorActive ? 'active' : ''}`} to="/editor">
                New Article
              </Link>
              <Link className={`navbar-link ${isActive('/settings') ? 'active' : ''}`} to="/settings">
                Settings
              </Link>
              <button
                type="button"
                className={`navbar-link navbar-button ${isProfileActive ? 'active' : ''}`}
                onClick={() => {
                  logout()
                  navigate('/login')
                }}
              >
                Logout
              </button>
              <Link
                className={`navbar-link ${isProfileActive ? 'active' : ''}`}
                to={`/profile/${user?.username}`}
              >
                {user?.username}
              </Link>
            </>
          ) : (
            <>
              <Link className={`navbar-link ${isActive('/login') ? 'active' : ''}`} to="/login">
                Sign in
              </Link>
              <Link className={`navbar-link ${isActive('/register') ? 'active' : ''}`} to="/register">
                Sign up
              </Link>
            </>
          )}
        </nav>
      </div>
    </header>
  )
}

function App() {
  const bootstrap = useAuthStore((state) => state.bootstrap)

  useEffect(() => {
    bootstrap()
  }, [bootstrap])

  return (
    <div>
      <NavBar />
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/login" element={<LoginPage />} />
        <Route path="/register" element={<RegisterPage />} />
        <Route path="/article/:slug" element={<ArticlePage />} />
        <Route element={<RequireAuth />}>
          <Route path="/editor" element={<EditorPage />} />
          <Route path="/editor/:slug" element={<EditorPage />} />
          <Route path="/settings" element={<SettingsPage />} />
        </Route>
        <Route path="/profile/:username" element={<ProfilePage />} />
        <Route path="/profile/:username/favorites" element={<ProfilePage />} />
      </Routes>
      <footer className="hero" style={{ marginTop: '3rem' }}>
        <div className="container">
          <p>RealWorld implementation built with Vue 3, Vite, and Pinia.</p>
        </div>
      </footer>
    </div>
  )
}

export default App

// apps/vue/src/App.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { RouterLink, RouterView, useRoute } from 'vue-router'
import { useAuthStore } from './stores/auth'

const authStore = useAuthStore()
const route = useRoute()
const currentUser = computed(() => authStore.user)

onMounted(() => {
  authStore.bootstrap()
})

const isActive = (path: string) => route.path === path
</script>

<template>
  <div>
    <header class="navbar">
      <div class="container navbar-content">
        <RouterLink to="/" class="navbar-logo">conduit</RouterLink>
        <nav class="navbar-links">
          <RouterLink :class="['navbar-link', { active: isActive('/') }]" to="/">
            Home
          </RouterLink>
          <template v-if="currentUser">
            <RouterLink
              :class="['navbar-link', { active: isActive('/editor') }]"
              to="/editor"
            >
              New Article
            </RouterLink>
            <RouterLink
              :class="['navbar-link', { active: isActive('/settings') }]"
              to="/settings"
            >
              Settings
            </RouterLink>
            <RouterLink
              :class="['navbar-link', { active: route.path.startsWith('/profile') }]"
              :to="`/profile/${currentUser.username}`"
            >
              {{ currentUser.username }}
            </RouterLink>
          </template>
          <template v-else>
            <RouterLink :class="['navbar-link', { active: isActive('/login') }]" to="/login">
              Sign in
            </RouterLink>
            <RouterLink
              :class="['navbar-link', { active: isActive('/register') }]"
              to="/register"
            >
              Sign up
            </RouterLink>
          </template>
        </nav>
      </div>
    </header>
    <main>
      <RouterView />
    </main>
    <footer class="hero" style="margin-top: 3rem">
      <div class="container">
        <p>RealWorld implementation built with Vue 3, Vite, and Pinia.</p>
      </div>
    </footer>
  </div>
</template>
