// app/src/components/ArticlePreview.vue
<script setup>
import { useAuthStore } from '../store/auth';
import api from '../services/api';
import { RouterLink } from 'vue-router';
import { ref, toRefs } from 'vue';

const { article } = toRefs(
  defineProps({
    article: { type: Object, required: true },
  }),
);

const emit = defineEmits(['update-article']);
const auth = useAuthStore();
const toggling = ref(false);

const toggleFavorite = async () => {
  if (!auth.isAuthenticated) return;
  toggling.value = true;
  try {
    const updated = article.value.favorited
      ? await api.unfavoriteArticle(article.value.slug)
      : await api.favoriteArticle(article.value.slug);
    emit('update-article', updated);
  } finally {
    toggling.value = false;
  }
};
</script>

<template>
  <div class="article-preview">
    <div class="article-meta">
      <RouterLink :to="{ name: 'profile', params: { username: article.author.username } }">
        <img :src="article.author.image" alt="author avatar" />
      </RouterLink>
      <div class="info">
        <RouterLink class="author" :to="{ name: 'profile', params: { username: article.author.username } }">
          {{ article.author.username }}
        </RouterLink>
        <span class="date">{{ new Date(article.createdAt).toDateString() }}</span>
      </div>
      <button
        class="btn btn-sm pull-xs-right"
        :class="article.favorited ? 'btn-primary' : 'btn-outline-primary'"
        :disabled="toggling"
        @click="toggleFavorite"
      >
        <i class="ion-heart"></i> {{ article.favoritesCount }}
      </button>
    </div>

    <RouterLink class="preview-link" :to="{ name: 'article', params: { slug: article.slug } }">
      <h1>{{ article.title }}</h1>
      <p>{{ article.description }}</p>
      <span>Read more...</span>
      <ul class="tag-list">
        <li class="tag-default tag-pill tag-outline" v-for="tag in article.tagList" :key="tag">{{ tag }}</li>
      </ul>
    </RouterLink>
  </div>
</template>

// apps/react/src/components/ArticlePreview.tsx
import { Link } from 'react-router-dom'
import type { Article } from '../services/api'

type Props = {
  article: Article
  onToggleFavorite?: (article: Article) => void
}

const ArticlePreview = ({ article, onToggleFavorite }: Props) => {
  const formattedDate = new Date(article.createdAt).toLocaleDateString()

  return (
    <article className="article-preview">
      <div className="flex-between">
        <div className="article-meta">
          <Link to={`/profile/${article.author.username}`}>
            <img src={article.author.image || 'https://static.productionready.io/images/smiley-cyrus.jpg'} alt="author" />
          </Link>
          <div>
            <Link to={`/profile/${article.author.username}`}>
              <strong>{article.author.username}</strong>
            </Link>
            <div>{formattedDate}</div>
          </div>
        </div>
        <button className="button secondary" type="button" onClick={() => onToggleFavorite?.(article)}>
          ❤ {article.favoritesCount}
        </button>
      </div>
      <Link to={`/article/${article.slug}`}>
        <h3 style={{ marginBottom: '0.35rem' }}>{article.title}</h3>
        <p className="helper-text" style={{ margin: 0 }}>
          {article.description}
        </p>
      </Link>
      <div className="tag-list" style={{ marginTop: '0.75rem' }}>
        {article.tagList.map((tag) => (
          <span key={tag} className="tag-pill">
            {tag}
          </span>
        ))}
      </div>
    </article>
  )
}

export default ArticlePreview
