// vue-app/src/components/SearchBox.vue
<script setup lang="ts">
defineProps<{
  value: string;
  placeholder?: string;
}>();

const emit = defineEmits<{
  (e: 'update:value', value: string): void;
}>();

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit('update:value', target.value);
};
</script>

<template>
  <div class="flex flex-1 items-center gap-2">
    <label for="search" class="sr-only">Search items</label>
    <input
      id="search"
      type="search"
      :value="value"
      :placeholder="placeholder ?? 'Search by name, SKU, or description'"
      class="w-full rounded border border-slate-300 px-3 py-2 text-sm"
      @input="handleInput"
    />
  </div>
</template>

// svelte-app/src/components/SearchBox.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let value = '';
  export let placeholder = 'Search by name, SKU, or description';

  const dispatch = createEventDispatcher<{ change: string }>();

  function handleInput(event: Event) {
    const target = event.target as HTMLInputElement;
    dispatch('change', target.value);
  }
</script>

<div class="flex flex-1 items-center gap-2">
  <label for="search" class="sr-only">Search items</label>
  <input
    id="search"
    type="search"
    class="w-full rounded border border-slate-300 px-3 py-2 text-sm"
    {placeholder}
    bind:value
    on:input={handleInput}
  />
</div>
