// app/src/components/ArticleMeta.vue
<script setup>
import { computed, ref, toRefs } from 'vue';
import { RouterLink } from 'vue-router';
import api from '../services/api';
import { useAuthStore } from '../store/auth';

const { article } = toRefs(
  defineProps({
    article: { type: Object, required: true },
  }),
);

const emit = defineEmits(['refresh', 'edit', 'delete']);
const auth = useAuthStore();
const busy = ref(false);

const isAuthor = computed(() => auth.username === article.value.author.username);

const toggleFollow = async () => {
  if (!auth.isAuthenticated) return;
  busy.value = true;
  try {
    const updatedProfile = article.value.author.following
      ? await api.unfollow(article.value.author.username)
      : await api.follow(article.value.author.username);
    emit('refresh', { ...article.value, author: updatedProfile });
  } finally {
    busy.value = false;
  }
};

const toggleFavorite = async () => {
  if (!auth.isAuthenticated) return;
  busy.value = true;
  try {
    const updated = article.value.favorited
      ? await api.unfavoriteArticle(article.value.slug)
      : await api.favoriteArticle(article.value.slug);
    emit('refresh', updated);
  } finally {
    busy.value = false;
  }
};
</script>

<template>
  <div class="article-meta">
    <RouterLink :to="{ name: 'profile', params: { username: article.author.username } }">
      <img :src="article.author.image" alt="author avatar" />
    </RouterLink>
    <div class="info">
      <RouterLink class="author" :to="{ name: 'profile', params: { username: article.author.username } }">
        {{ article.author.username }}
      </RouterLink>
      <span class="date">{{ new Date(article.createdAt).toDateString() }}</span>
    </div>

    <template v-if="isAuthor">
      <button class="btn btn-outline-secondary btn-sm" @click="emit('edit')">
        <i class="ion-edit"></i> Edit Article
      </button>
      <button class="btn btn-outline-danger btn-sm" :disabled="busy" @click="emit('delete')">
        <i class="ion-trash-a"></i> Delete Article
      </button>
    </template>
    <template v-else>
      <button class="btn btn-sm btn-outline-secondary" :disabled="busy" @click="toggleFollow">
        <i class="ion-plus-round"></i>
        {{ article.author.following ? 'Unfollow' : 'Follow' }} {{ article.author.username }}
      </button>
      <button class="btn btn-sm" :class="article.favorited ? 'btn-primary' : 'btn-outline-primary'" :disabled="busy" @click="toggleFavorite">
        <i class="ion-heart"></i>
        {{ article.favorited ? 'Unfavorite' : 'Favorite' }} Post ({{ article.favoritesCount }})
      </button>
    </template>
  </div>
</template>

// apps/svelte/src/components/ArticleMeta.svelte
<script>
  import { token } from '../stores/auth'
  import { articles as articleApi, profiles as profilesApi } from '../services/api'
  import { createEventDispatcher } from 'svelte'
  import { get } from 'svelte/store'

  export let article
  const dispatch = createEventDispatcher()

  const currentToken = token

  async function toggleFavorite() {
    if (!get(currentToken)) return dispatch('favorite', article)
    const method = article.favorited ? articleApi.unfavorite : articleApi.favorite
    const response = await method(get(currentToken), article.slug)
    dispatch('favorite', response.article)
  }

  async function toggleFollow() {
    if (!get(currentToken)) return
    const method = article.author.following ? profilesApi.unfollow : profilesApi.follow
    const response = await method(get(currentToken), article.author.username)
    article = { ...article, author: response.profile }
  }
</script>

<div class="article-meta">
  <a href={`/profile/${article.author.username}`}>
    <img src={article.author.image || 'https://static.productionready.io/images/smiley-cyrus.jpg'} alt={article.author.username} />
  </a>
  <div class="info">
    <a href={`/profile/${article.author.username}`} class="author">{article.author.username}</a>
    <span class="date">{new Date(article.createdAt).toDateString()}</span>
  </div>
  <button class="btn small" on:click={toggleFollow}>
    {article.author.following ? 'Unfollow' : 'Follow'} {article.author.username}
  </button>
  <button class="btn small" on:click={toggleFavorite}>
    ❤ {article.favoritesCount}
  </button>
</div>
