// apps/vue/src/components/Pagination.vue
<script setup>
import { computed, toRefs } from 'vue';

const { total, currentPage, limit } = toRefs(
  defineProps({
    total: { type: Number, required: true },
    currentPage: { type: Number, default: 1 },
    limit: { type: Number, default: 10 },
  }),
);

const emit = defineEmits(['change-page']);

const pages = computed(() => {
  const count = Math.ceil(total.value / limit.value);
  return Array.from({ length: count }, (_, i) => i + 1);
});
</script>

<template>
  <nav v-if="pages.length > 1">
    <ul class="pagination">
      <li
        v-for="page in pages"
        :key="page"
        class="page-item"
        :class="{ active: page === currentPage }"
        @click="emit('change-page', page)"
      >
        <a class="page-link" href="#">{{ page }}</a>
      </li>
    </ul>
  </nav>
</template>

// apps/svelte/src/components/Pagination.svelte
<script>
  import { createEventDispatcher } from 'svelte'

  export let total = 0
  export let limit = 10
  export let current = 0

  const dispatch = createEventDispatcher()

  $: pages = Math.ceil(total / limit)
  $: numbers = Array.from({ length: pages }, (_, i) => i)

  function select(page) {
    dispatch('change', page)
  }
</script>

{#if pages > 1}
  <ul class="pagination">
    {#each numbers as n}
      <li class:active={n === current} on:click={() => select(n)}>{n + 1}</li>
    {/each}
  </ul>
{/if}
